# 3.7 Joins and Merges

In [1]:
import pandas as pd
df = pd.read_csv('senator_tweets.csv')

In [12]:
df

,Unnamed: 0,created_at,text,url,replies,retweets,favorites,user,bioguide_id,party,state
0,0,10/19/2017 21:47,We released bipartisan healthcare bill today &...,https://twitter.com/amyklobuchar/status/921130...,21,129,533,amyklobuchar,K000367,D,MN
1,1,10/19/2017 18:48,I spoke with @Morning_Joe team abt #HonestAds ...,https://twitter.com/amyklobuchar/status/921085...,8,46,150,amyklobuchar,K000367,D,MN
2,2,10/19/2017 18:14,Lots of interest in my bill with Senators Warn...,https://twitter.com/amyklobuchar/status/921077...,36,227,932,amyklobuchar,K000367,D,MN
3,3,10/19/2017 18:04,"Today's the day @MarkWarner, @SenJohnMcCain &a...",https://twitter.com/amyklobuchar/status/921074...,17,167,550,amyklobuchar,K000367,D,MN
4,4,10/19/2017 16:33,".@MarkWarner, @SenJohnMcCain &amp; I put toget...",https://twitter.com/amyklobuchar/status/921051...,31,279,893,amyklobuchar,K000367,D,MN
...,...,...,...,...,...,...,...,...,...,...,...
288610,288610,7/28/2015 15:33,Such a zone would allow the flow of unfettered...,https://twitter.com/timkaine/status/6260527578...,0,4,1,timkaine,K000384,D,VA
288611,288611,7/28/2015 15:32,I welcome greater cooperation between the U.S....,https://twitter.com/timkaine/status/6260526304...,2,7,2,timkaine,K000384,D,VA
288612,288612,7/27/2015 17:34,Educacií_n sobre la prevencií_n del abuso sexu...,https://twitter.com/timkaine/status/6257210135...,0,1,0,timkaine,K000384,D,VA
288613,288613,7/27/2015 17:30,Education on sexual assault prevention should ...,https://twitter.com/timkaine/status/6257198751...,4,5,1,timkaine,K000384,D,VA
288614,288614,7/26/2015 17:15,"25 years since passage, the ADA has helped ens...",https://twitter.com/timkaine/status/6253537947...,1,13,17,timkaine,K000384,D,VA

In [9]:
bio_df = pd.read_csv('senator_bio.csv')

In [10]:
bio_df

  bioguide                                           bio_text
0  K000367  When I was younger I would sit underneath the ...
1  H001076  I always loved trains especially ones powered ...
2  B001267  Education has never been more important to me ...
3   A99939  Mass exodus to Mars has always been my backup ...

In [17]:
df = df.merge(bio_df, left_on='bioguide_id', right_on='bioguide', how='right', inplace=True)